- name: Create private key with password protection
  community.crypto.openssl_privatekey:
    path: "{{ root_ca_path_to_privatekey }}"
    passphrase: "{{ root_ca_secret_ca_passphrase }}"
    cipher: auto
  notify: Restart CA

- name: Create certificate signing request (CSR) for Root CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ root_ca_path_to_privatekey }}"
    privatekey_passphrase: "{{ root_ca_secret_ca_passphrase }}"
    common_name: "{{ ca_common_name }} Root CA"
    crl_distribution_points: "{{ root_ca_crl_distribution_points }}"
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
      - cRLSign
    key_usage_critical: true
  register: root_ca_csr

- name: Create self-signed Root CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ root_ca_path_to_cert }}"
    csr_content: "{{ root_ca_csr.csr }}"
    privatekey_path: "{{ root_ca_path_to_privatekey }}"
    privatekey_passphrase: "{{ root_ca_secret_ca_passphrase }}"
    provider: selfsigned
    selfsigned_not_after: "{{ root_ca_validity_period }}"
    force: true
  notify: Restart CA
