---
# handlers file for ansible-role-step-ca
- name: Restart CA
  ansible.builtin.systemd_service:
    name: step-ca
    state: restarted

- name: Restart CRL endpoint
  ansible.builtin.systemd_service:
    name: crl
    state: restarted